Library_Management/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Library_Management.Data;
using Library_Management.Models;
using Library_Management.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace Library_Management.Controllers
{
    public class BookController : Controller
    {
        private readonly BookRepository _bookRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment = null;

       

        public BookController(BookRepository bookRepository, IWebHostEnvironment webHostEnvironment)
        {
           
            _bookRepository = bookRepository;
            _webHostEnvironment = webHostEnvironment;
            
        }

        //public List<BookModel> GetAllBooks()
        // {
        //     return _bookRepository.GetAllBooks();
        // }

        public async Task<ViewResult> GetAllBooks(string sname)
        {
            var data = await _bookRepository.GetAllBooks();
            return View(data);
        }


        //[Route("book-details/{id}")]
        public async Task<ViewResult> GetBook(int id  /*string bookname*/)
        {
            var detailsdata = await _bookRepository.GetBooksById(id);
            return View(detailsdata);
        }

        [Authorize(Roles = "Admin, Manager")]
        public ViewResult AddNewBook(bool isSuccess = false, int bookId = 0)
        {

            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View();
        }

        [HttpPost]
        [Authorize(Roles ="Admin, Manager")]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
            if (ModelState.IsValid)
            {

                if (bookModel.CoverPhoto!=null)
                {
                    string folder = "books/cover/";
                   bookModel.CoverImageUrl =  await UploadImage(folder, bookModel.CoverPhoto);

                }

                if (bookModel.GalleryFiles != null)
                {
                    string folder = "books/Gallery/";
                    bookModel.Gallery = new List<GalleryModel>();
                    foreach (var item in bookModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = item.FileName,
                            URL = await UploadImage(folder, item)
                        };
                        bookModel.Gallery.Add(gallery);
                    }
                }


                var ext = Path.GetExtension(bookModel.PdfBook.FileName);

                if (ext != "pdf")
                {
                    ViewBag.msg = "File Extension Is InValid - Only Upload PDF File";
                }
                if (bookModel.PdfBook != null)
                      {
                        string folder = "books/bookpdf/";
                        bookModel.PdfBookUrl = await UploadImage(folder, bookModel.PdfBook);

                       }

                int id = await _bookRepository.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(AddNewBook), new { isSuccess = true, bookId = id });
                }
            }
            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            //string folder = "books/cover/";

            folderPath += Guid.NewGuid().ToString() + " " + file.FileName;
          
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }

        [Authorize(Roles = "Admin, Manager")]
        public async Task<ViewResult> Delete(Books books, int id)
        {
            var detailsdata = await _bookRepository.GetBooksById(id);

            return View(detailsdata);
        }
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> DeleteConf(int id)
        {
            await _bookRepository.DeleteB(id);
            return RedirectToAction("GetAllBooks");
        }


      




        //public async Task<ViewResult> Edit(int id)
        //{
        //    var data = await _bookRepository.UpdateBook(Books);
        //    return View(data);
        //}
        //[HttpPost]
        //public async Task<IActionResult> Edit(BookModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        await _bookRepository.UpdateBook(model.Id, model);
        //        return RedirectToAction("GetAllBooks");
        //    }
        //    return View();

        //}




    }
}

Library_Management/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Library_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Library_Management.Repository;

namespace Library_Management.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly BookRepository _bookRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment = null;
        private readonly ILogger<HomeController> _logger;

       
        

        public HomeController(ILogger<HomeController> logger, BookRepository bookRepository, IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }
       [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Index(int id)
        {
            var detailsdata = await _bookRepository.GetBooksById(id);
            return View(detailsdata);

            //return View();
        }

        public ViewResult AboutUs()
        {
            return View();
        }

        public ViewResult ContactUs()
        {
            return View();
        }


        [Authorize(Roles = "Manager")]
         public IActionResult ManagerPage()
         {
         return View();
         }

      [Authorize]
      public IActionResult UserPage()
      {
            
           return View();
      }

      //  public IActionResult Privacy()
      //  {
      //      return View();
      //  }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Library_Management/Controllers/RoleVMsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_Management.Data;
using Library_Management.Models;
using Microsoft.AspNetCore.Identity;

namespace Library_Management.Controllers
{
    public class RoleVMsController : Controller
    {
        private readonly AuthDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleVMsController(AuthDbContext context, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
        }

        // GET: RoleVMs
        public IActionResult Index()
        {
            var roles =  _roleManager.Roles.ToList();

            List<RoleVM> vm = new List<RoleVM>();
            foreach (var item in roles)
            {
                vm.Add(
                    new RoleVM
                    {
                        Id = item.Id,
                        Name = item.Name
                    });

            }


            return View(vm);
        }

        // GET: RoleVMs/Details/5
        public IActionResult Details(string id)
        {
            var roles = _roleManager.Roles.Where(x => x.Id == id).FirstOrDefault();

            RoleVM vm = new RoleVM();

            vm.Id = roles.Id;
            vm.Name = roles.Name;

            return View(vm);
        }

        // GET: RoleVMs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoleVMs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( RoleVM roleVM)
        {
            if (ModelState.IsValid)
            {
                //_context.Add(roleVM);
                //await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));

                bool ext = await _roleManager.RoleExistsAsync(roleVM.Name);
                if (ext)
                {
                    ViewBag.msg = "Role Already Exists";
                    return View();
                }

              await  _roleManager.CreateAsync(new IdentityRole(roleVM.Name));
            
            }
            return RedirectToAction("Index");
        }

        // GET: RoleVMs/Edit/5
        public IActionResult Edit(string id)
        {
            //if (id == null)
            //{
            //    return NotFound();
            //}

            //var roleVM = await _context.RoleVM.FindAsync(id);
            //if (roleVM == null)
            //{
            //    return NotFound();
            //}
            var roles = _roleManager.Roles.Where(x=>x.Id==id).FirstOrDefault();

            RoleVM vm = new RoleVM();

            vm.Id = roles.Id;
            vm.Name = roles.Name;

            return View(vm);
        }

        // POST: RoleVMs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, RoleVM roleVM)
        {
            if (id != roleVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var role = _roleManager.Roles.Where(x => x.Id == id).FirstOrDefault();
                    role.Name = roleVM.Name;
                    await _roleManager.UpdateAsync(role);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleVMExists(roleVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roleVM);
        }

        // GET: RoleVMs/Delete/5
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roles = _roleManager.Roles.Where(x => x.Id == id).FirstOrDefault();

            RoleVM vm = new RoleVM();

            vm.Id = roles.Id;
            vm.Name = roles.Name;

           // return View(vm);
            if (vm == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        // POST: RoleVMs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var roles = _roleManager.Roles.Where(x => x.Id == id).FirstOrDefault();

            RoleVM vm = new RoleVM();

            vm.Id = roles.Id;
            vm.Name = roles.Name;

            await _roleManager.DeleteAsync(roles);

            return RedirectToAction("Index");
           
        }

        private bool RoleVMExists(string id)
        {
            return _context.RoleVM.Any(e => e.Id == id);
        }




    }
}

Library_Management/Controllers/UserSystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library_Management.Areas.Identity.Data;
using Library_Management.Data;
using Library_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Library_Management.Controllers
{
     // [Authorize]
    public class UserSystemController : Controller
    {
        private readonly AuthDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IPasswordHasher<ApplicationUser> _passwordhasher;
        public IEnumerable<ApplicationUser> ApplicationUserList;
        public ApplicationUser ApplicationUserSingle;


        public UserSystemController(AuthDbContext context, UserManager<ApplicationUser> userManager, IPasswordHasher<ApplicationUser> passwordhasher, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _passwordhasher = passwordhasher;
            _roleManager = roleManager;
        }

        [Authorize(Roles ="Admin, Manager")]
        public IActionResult Index()
        {
            ApplicationUserList = _context.ApplicationUser.ToList();
            return View(ApplicationUserList);

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task< IActionResult>  Create(ApplicationUser model, string password, int Id)
        {

            IdentityResult identityResult = await _userManager.CreateAsync(model, password);

            return RedirectToAction("index");
        }
        public  IActionResult Edit(string Id )
        {

           
            ApplicationUserSingle = _context.ApplicationUser.Find(Id);


            return View(ApplicationUserSingle);
        }
        [HttpPost]
        public IActionResult Edit(ApplicationUser model, string password)
        {
            ApplicationUserSingle  = _context.ApplicationUser.Find(model.Id);

            ApplicationUserSingle.StudentId = model.StudentId;
            ApplicationUserSingle.StudentName = model.StudentName;
            ApplicationUserSingle.UserName = model.UserName;
            ApplicationUserSingle.Email = model.UserName;
            if (!string.IsNullOrEmpty(password))
            {
                ApplicationUserSingle.PasswordHash = _passwordhasher.HashPassword(model, password);
            }

            _context.Update(ApplicationUserSingle);
            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }

        public  IActionResult Details(string Id)
        {
            ApplicationUserSingle = _context.ApplicationUser.Find(Id);
            return View(ApplicationUserSingle);
        }

        public IActionResult Delete(string Id)
        {
            ApplicationUserSingle = _context.ApplicationUser.Find(Id);
           
            return View(ApplicationUserSingle);
            
        }
        [HttpPost]
        public async Task <IActionResult> Delete(ApplicationUser model)
        {
            ApplicationUserSingle = _context.ApplicationUser.Find(model.Id);
            await _userManager.DeleteAsync(ApplicationUserSingle);

            return RedirectToAction("Index");
        }

        public IActionResult AssignRole(string id)
        {

            var users = _context.ApplicationUser.Where(x => x.Id == id).SingleOrDefault();
            var userRoles = _context.UserRoles.Where(x => x.UserId == id).Select(x => x.RoleId).ToList();
            ManageUserRole userRolesVM = new ManageUserRole();
            userRolesVM.AppUser = users;
            userRolesVM.Roles = _roleManager.Roles.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id,
                Selected = userRoles.Contains(x.Id)
            }).ToList();

            return View(userRolesVM);
        }


        [HttpPost]
        public IActionResult AssignRole(ManageUserRole model)
        {

            var selectedRoleId = model.Roles.Where(x => x.Selected).Select(x => x.Value);
            var alreadyExitsRoleId = _context.UserRoles.Where(x => x.UserId == model.AppUser.Id).Select(x => x.RoleId).ToList();
            var toAdd = selectedRoleId.Except(alreadyExitsRoleId);
            var toRemove = alreadyExitsRoleId.Except(selectedRoleId);

            foreach (var item in toRemove)
            {
                _context.UserRoles.Remove(new IdentityUserRole<string>
                {
                    RoleId = item,
                    UserId = model.AppUser.Id
                });
            }

            foreach (var item in toAdd)
            {
                _context.UserRoles.Add(new IdentityUserRole<string>
                {
                    RoleId = item,
                    UserId = model.AppUser.Id
                });
            }
            _context.SaveChanges();

            return RedirectToAction("Index");
        }



    }
}

Library_Management/Views/Home/users/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="preload" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'" rel="preload">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">


                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="ManagerPage">
                    Library Management System
                </a>

                <partial name="_LoginPartial.cshtml" />


                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="UserSystem" asp-action="Index">View User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="RoleVMs" asp-action="Index">RoleVM</a>
                </li>*@
                        @*<li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>*@

                        @*<li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact</a>
                </li>*@
                        @*<li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="GetAllBooks">GetAllBooks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="AddNewBook">AddNewBook</a>
                </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-protocol="http" asp-host="ratul.intels.co" asp-controller="Home" asp-action="Index">Ratul</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            Copyright &copy; Library Management @DateTime.Now.Year
        </div>
    </footer>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>